version: '3'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          CACHEBUST: $(date +%s)
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development  
    command: npm run dev
    ports:
      - 3000:3000


