version: '3.7'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENV NODE_ENV=development
    ports:
      - 3000:3000