version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development    
    ports:
      - 3000:3000
      - 9229:9229