name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.ci.yml" up -d --build

      - name: Lint code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run lint

      - name: Format code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run format

      - name: Setup Prisma
        run: docker-compose -f "docker-compose.ci.yml" run app npm run migrate:dev

      - name: Run unit tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test

      - name: Run E2E tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:e2e

      - name: Stop containers
        run: docker-compose -f "docker-compose.ci.yml" down